require('packer_init')

require('user/impatient')

require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('core/statusline')

require('user/nvim-tree')
require('user/indent-blankline')
require('user/comment')
require('user/autopairs')
require('user/gitsigns')
require('user/toggleterm')
require('user/telescope')
require('user/nvim-cmp')
require('user/nvim-lsp')
require('user/nvim-treesitter')
require('user/vim-test')
